### ISSUE TITLE
stategy to fix the "exists" function ?

### ISSUE THREAD

**Issue by yzerlaut** [HumanBrainProject/fairgraph#20]
The exists function doesn't work for all the classes that do not have a "name" field (e.g. Person).

this is because of the existence query defined by (see =base.py= _:
```
    @property
    def _existence_query(self):
        # Note that this default implementation should in
        # many cases be over-ridden.
        # It assumes that "name" is unique within instances of a given type,
        # which may often not be the case.
        return {
            "path": "schema:name",
            "op": "eq",
            "value": self.name
        }
```

What's the idea to solve this ? Shouldn't the existence query be set in the Class definition and otherwise, by default, we load this "name" query ?

**Comment by apdavison** [comment]
I've now refactored the existence query idea so that it works for the KG Query API as well as for the Nexus API. Now you have to set the class attribute `existence_query_fields`.

By default, this is `("name",)`, for Person it is `("family_name", "given_name")`, etc. I don't yet have tests for all classes, probably there are still some for which the default value needs to  be over-ridden.

**Comment by yzerlaut** [comment]
Perfect !
